name: Testar servidor

on:
  workflow_dispatch:

jobs:
  teste:
    runs-on: self-hosted

    steps:
      - name: Verificar servidor
        run: |
          echo "=== SERVIDOR ==="
          hostname

          echo "=== USUARIO ==="
          whoami

          echo "=== SISTEMA ==="
          uname -a

          echo "=== NODE ==="
          node --version
